### ISSUE TITLE
Setting the userType AFTER login

### ISSUE THREAD

**Issue by aufdenpunkt** [neroniaky/angular2-token#137]
Hi,

is it possible to set the user type after the login action? In our application I'm logging in with my email and password and the backend knows which type of user I am.

Thanks and best,
Chris

**Comment by neroniaky** [comment]
Hey Chris, I guess we have to specify user type a little more, because there are multiple ways to solve this.

When `angular2-token` talks about user types it means that you user different user tables/models, which use different routes. For example, the admin signs in  via `/admin/auth` and the user via `user/auth`.

In your case it sounds more like you have one model/table for all users and a column which defines the user type, like `ADMIN` etc, but you always sign in via the `/user/auth`-route (example).

Can you tell me a little more about your implementation? Thanks!

**Comment by neroniaky** [comment]
Gonna close this for now.

**Comment by betosalvador** [comment]
Hello, @neroniaky 

I have a similar problem.

Just like you said.

I have one Users table in my api, but each user has one role.

There is any way to keep this role in the session?

I need this to show or hide some elements on the page (like an authorize process).

THank you very much

**Comment by arjenbrandenburgh** [comment]
This was answered in #435
