### ISSUE TITLE
User roles

### ISSUE THREAD

**Issue by ghosthope** [neroniaky/angular2-token#238]
Hi!
Could you explain how use this library with different user roles? Why must I set an user role in signIn data if I know only login and password?

**Comment by neroniaky** [comment]
Hey @ghosthope. There are multiple ways to handle a multi-user setups. The frontend only needs to know about if you use the multi user model setup explained [here](https://github.com/plataformatec/devise/wiki/How-to-Setup-Multiple-Devise-User-Models). Thats because you need to handle different routes for different user types, like `/admin/auth` for admin or `/user/auth` for user.
For the default behavior you don't need to set a user type.
