### ISSUE TITLE
Local storage not set after sign in

### ISSUE THREAD

**Issue by implicitdef** [neroniaky/angular2-token#3]
After a successful call to `_tokenService.signIn`, the local storage is left untouched, so the following calls to `get`/`post`/etc. never send the authentication headers.

It seems the `signIn` method is just missing a call to `_setAuthData`.

**Comment by neroniaky** [comment]
@implicitdef did you add `:expose  => ['access-token', 'expiry', 'token-type', 'uid', 'client']` to your CORS configuration? Otherwise Rails doesn't add the `Access-Control-Expose-Headers` to the sign-in response in which case the service can't access the headers and doesn't set the local storage.
Thanks for your feedback!

**Comment by implicitdef** [comment]
Right, I missed that, thanks.

**Comment by mattsketchy** [comment]
thanks @neroniaky for your answer!!
