### ISSUE TITLE
Use with canActivate

### ISSUE THREAD

**Issue by malina** [neroniaky/angular2-token#7]
Hi!

I have question.
I use angular2-token.

I try implements canActivate with angular2-token but have problem.
On first page load (or if click reload button in browser) currentUserData is undefined.

What could be the problem?

```

import { Injectable } from '@angular/core';
import { CanActivate, Router, ActivatedRouteSnapshot, RouterStateSnapshot } from '@angular/router';

import { Angular2TokenService } from 'angular2-token';

@Injectable()
export class CanActivateViaAuthGuard implements CanActivate {

  constructor(private authService: Angular2TokenService, private router: Router) {}

  private _canActivate: boolean = true;
  canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): any {
    // this undefined
    if (this.authService.currentUserData) {
      return true;
    } else {
      this.router.navigate(['/login']);
      return false;
    }
  }
}

```

**Comment by neroniaky** [comment]
Hi @malina, thanks for your feedback. 
I haven't tried it with CanActivate yet. CanActivate probably triggers before the .init() call, so current user isn't set. Gonna need some time to look into it.

**Comment by neroniaky** [comment]
I added Route Guard support, so you can use Angular2-Token directly. You can find an example [here](https://github.com/neroniaky/angular2-token#route-guards).

I also added an showcase / example to the angular2-token-example repository [here](https://github.com/neroniaky/angular2-token-example).

In general you have to call `.init()` at the same or at a higher level component where you first use the service, otherwise currentUserData can be undefined (its always undefined if no user is logged in).

Please let me know if this helped.

**Comment by malina** [comment]
Thank you for answer.
But if open https://angular2-token.herokuapp.com/#/restricted
I see white page, that is the router is not activated.

**Comment by neroniaky** [comment]
The behavior should be:
User logged in --> text on page
User **not** logged in --> no text on page (the link button on the main page does not work either)

**Comment by neroniaky** [comment]
Closed because no response in 7 Days. If you have an further question please use the gitter chat. Thank you!
